### ISSUE TITLE
mac aarch64 binary

### ISSUE THREAD

**Issue by borkdude** [babashka/tools-deps-native#24]

**Comment by TimoKramer** [comment]
I could use the aarch64 binaries for linux, mac and windows. Is there anything to consider when adding the builds? Just copy them over from your other repos?

**Comment by TimoKramer** [comment]
> windows aarch64? that's something I haven't done before. and sure.

oh, right. you don't have windows arm anywhere!? then I will pass on that as well for now...

**Comment by borkdude** [comment]
Done, thanks @TimoKramer
